benches/bench.rs, shred-derive/src/lib.rs
=> Cleanup: Fix warnings and reformatting

Cargo.toml, examples/generic_derive.rs, shred-derive/Cargo.toml, shred-derive/src/lib.rs
Fixes #1
+ support for lifetimes
+ support for type parameters
+ add example with type parameter
=> Make #[derive(SystemData)] more flexible

.travis.yml, Cargo.toml, examples/seq_dispatch.rs, src/dispatch.rs, src/lib.rs
=> Sequential Dispatching

benches/bench.rs, src/cell.rs, src/dispatch.rs, src/res.rs
Now the crate follows the API guidelines better.
=> #[derive] Debug and Default

examples/custom_bundle.rs, shred-derive/src/lib.rs, src/cell.rs, src/dispatch.rs, src/res.rs
Wow, I didn't realize these bugs the first time I wrote this code.
=> Fix TrustCell and another critical bug

Cargo.toml, src/dispatch.rs, src/lib.rs
We are not using other rayon parts anyway.
=> Use rayon-core instead of rayon

README.md, benches/bench.rs, examples/basic_dispatch.rs, examples/seq_dispatch.rs, examples/thread_local.rs, src/dispatch.rs, src/lib.rs, src/system.rs, tests/dispatch.rs
In a discussion on Gitter, this seemed to be more familiar to most users.
=> Rename System::work to run

examples/derive_bundle.rs, examples/generic_derive.rs, shred-derive/src/lib.rs
=> Improve generic_derive example

src/res.rs
Users of the existing methods may wish to handle the error, so the new methods will return `None` in the case of a requested resource not existing.
=> Add `try_*` variants to methods on Resources that return an Option instead of panicking

Cargo.toml
New version provides try_fetch variants.
Sorry, planned to publish it by Monday, but didn't find any time to do so.
=> Bump version to 0.4.3

Cargo.toml, src/dispatch/async.rs
Updates the rayon dependency version to 0.8.
=> Update rayon version

Cargo.toml, examples/fetch_opt.rs, src/res.rs
=> Add optional fetching of resources

Cargo.toml, examples/basic_dispatch.rs, examples/fetch_opt.rs, examples/par_seq.rs, examples/seq_dispatch.rs, examples/thread_local.rs, src/dispatch/async.rs, src/dispatch/builder.rs, src/dispatch/dispatcher.rs, src/dispatch/par_seq.rs
and fix soundness issue with `AsyncDispatcher`
=> Take immutable references to `Resources`

src/system.rs
=> Add blanket impl SystemData for PhantomData

Cargo.toml, src/dispatch/builder.rs, src/lib.rs, src/res/mod.rs
`fxhash` is more efficient than `fnv` here.
=> Use `fxhash` instead of `fnv`

Cargo.toml, examples/async.rs, shred-derive/src/lib.rs, src/dispatch/async.rs, src/lib.rs
=> Fix async dispatcher

src/cell.rs, src/lib.rs, src/meta.rs, src/res/mod.rs
Still need to add documentation, but the logic is in place already.
=> Add `MetaTable`s

src/cell.rs, src/res/mod.rs
Also make some changes that should have no effect on functionality, but aid readability.
=> Add some docs

Cargo.toml, src/meta.rs
cc @Rhuagh @omni-viral @Xaeroxe @WaDelma 
I intend to release pre-release versions of shred and Specs today so we can check if everything is working as intended.
=> Make a 0.7-alpha1 pre-release

Cargo.toml, src/dispatch/builder.rs, src/dispatch/par_seq.rs, src/dispatch/stage.rs, src/lib.rs, src/res/mod.rs, src/system.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/shred/85)
=> fix: Make System take self during setup

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/slide-rs/shred/86)
=> fix: Readd nightly feature

src/dispatch/mod.rs, src/dispatch/par_seq.rs, src/dispatch/stage.rs, src/lib.rs
Just need this to name the type in places.
=> Expose RunWithPool, use replaced name value

src/dispatch/dispatcher.rs, src/dispatch/stage.rs
This could be useful for reducing CPU overhead in Amethyst
=> Add functions for determining the maximum useful thread count

.travis.yml, README.md, src/res/data.rs
=> Fix wrong documentation of ReadExpect

shred-derive/Cargo.toml, shred-derive/src/lib.rs
=> Updated to `syn 0.15` and `quote 0.6`.

README.md, benches/bench.rs, examples/async.rs, examples/basic_dispatch.rs, examples/custom_bundle.rs, examples/derive_bundle.rs, examples/dyn_sys_data.rs, examples/fetch_opt.rs, examples/generic_derive.rs, examples/par_seq.rs, examples/seq_dispatch.rs, examples/thread_local.rs, shred-derive/src/lib.rs, src/dispatch/async.rs, src/dispatch/builder.rs, src/dispatch/dispatcher.rs, src/dispatch/par_seq.rs, src/dispatch/stage.rs, src/lib.rs, src/meta.rs, src/res/data.rs, src/res/entry.rs, src/res/mod.rs, src/res/setup.rs, src/system.rs, tests/dispatch.rs, tests/nightly.rs
I renamed  'Resource' to 'World'  as stated in [this issue](https://github.com/slide-rs/specs/issues/523).
This PR is part 1 of two PR's described in the linked issue.
=> Renamed 'Resource' to 'World'

.travis.yml, README.md
=> Bump min Rust version to 1.30

examples/dyn_sys_data.rs, src/meta.rs, tests/meta_table_safety_113.rs
=> Prohibit possible memory bug with MetaTable

src/dispatch/dispatcher.rs, src/dispatch/stage.rs, src/system.rs
=> Add `{Dispatcher, RunNow, System}::dispose`

src/dispatch/dispatcher.rs, src/dispatch/stage.rs, src/system.rs, tests/dispose.rs
=> Make dispose self consuming

src/cell.rs, src/meta.rs, src/world/mod.rs
=> Implement World::remove

examples/dynamic_resource_id.rs, src/world/mod.rs
=> Implement dynamic resource IDs + example

.travis.yml, Cargo.toml, src/cell.rs, src/world/mod.rs
=> Print type name for cell borrow errors

Cargo.toml, examples/batch_dispatching.rs, src/cell.rs, src/dispatch/async_dispatcher.rs, src/dispatch/batch.rs, src/dispatch/batch_builder.rs, src/dispatch/builder.rs, src/dispatch/dispatcher.rs, src/dispatch/mod.rs, src/dispatch/stage.rs, src/lib.rs
This is the second iteration to implement the Batch dispatching following the feedback received in this PR: https://github.com/slide-rs/shred/pull/144 (Was easier for me redo everything rather change it)
This is the project to test this feature: 
[shred_test.zip](https://github.com/slide-rs/shred/files/3363344/shred_test.zip)
=> Implemented batch dispatching

src/dispatch/batch.rs
Improved Documentation of the function `create`.
This change explain where the dispatcher come from.
=> Improved Documentation of the function `create`

README.md
The example in the README.md is outdated and not working. This PR updates it to match the working example in the documentation.
=> Update README.md example to match working example from docs

CHANGELOG.md, ci-script.sh, examples/derive_bundle.rs, examples/seq_dispatch.rs, examples/thread_local.rs, src/lib.rs, src/system.rs, src/world/mod.rs, tests/dispatch.rs, tests/no_parallel.rs
https://github.com/amethyst/specs/issues/673
=> Remove Send+Sync resource requirement if parallel disabled

Cargo.toml
hey devs, could you please update hashbrown to 0.9 and publish a version on crates.io ?
thank you :)
=> update dependency: hashbrown 0.9

Cargo.toml, shred-derive/Cargo.toml, src/dispatch/builder.rs, src/world/entry.rs
=> Update dependency versions.

src/cell.rs
Fixes https://github.com/amethyst/shred/issues/185
=> Replace Ref{,Mut}::map with safer code
