amethyst/shred

Cargo.toml
README.md
benches/bench.rs
examples/basic_dispatch.rs
examples/custom_bundle.rs
examples/derive_bundle.rs
shred-derive/Cargo.toml
shred-derive/src/lib.rs
src/dispatch.rs
src/lib.rs
src/res.rs
src/system.rs

The name system is more appropriate because it is executed multiple times.

Rename task to system

---

benches/bench.rs
examples/basic_dispatch.rs
examples/seq_dispatch.rs
examples/thread_local.rs
src/dispatch.rs
src/lib.rs
src/system.rs
tests/dispatch.rs

The context is not necessary because you can always just use a Resource.

Remove the context type parameter

---

src/res.rs

When using type from other crate not every type implements `Debug`, and `Debug` is not use everywhere meaningfully anyway.

Remove `Debug` bound for `Resource` trait.

---

README.md
benches/bench.rs
examples/basic_dispatch.rs
examples/custom_bundle.rs
examples/derive_bundle.rs
examples/seq_dispatch.rs
examples/thread_local.rs
shred-derive/src/lib.rs
src/dispatch.rs
src/lib.rs
src/res.rs
src/system.rs
tests/dispatch.rs

Using `usize` for ids has several advantages:
* Easier to implement than hashed values because I only need to accept `usize`, no need for two variants (`Hash`-implementor and hashed value)
* No collisions of ids
---
Accepting the additional ids allows to actually have different system data for every id.

Change resource id to usize and make SystemData functions receive resource id

---

bors.toml

This is necessary for bors-ng to work.

Add `bors.toml`

---

.travis.yml

Otherwise, Travis would build against branch `staging.tmp`.

Only build against staging, trying and master

---

src/dispatch.rs

cc @nchashch
This is how I imagined to have those systems divided into stages:
```rust
let dispatcher = DispatcherBuilder::new()
.add(InputHandler, "handle_input", &[])
.add(NetworkSynchronizer, "netsync", &[])
.new_stage()
.add(ForceGenerator, "force", &[])
.add(Integrator, "integrator", &["force"])
.add(EnemySpawner)
.new_stage()
.add(Renderer, "render", &[])
.add(Audio, "audio", &[])
.build();
```
cc https://github.com/amethyst/amethyst/issues/238

Add Stages and dispatch tests

---

examples/custom_bundle.rs
shred-derive/src/lib.rs
src/dispatch.rs
src/res.rs
src/system.rs

This isn't necessary anymore, cannot cause undefined behavior. Using it wrong causes the thread to panic.

Remove unsafe marker from SystemData functions

---

src/dispatch/builder.rs

I have run into this error many times and it's not fun to find the source using `RUST_BACKTRACE`. This should help find the cause of the error quicker and more easily.

Include name of system that was not found in panic message

---

src/dispatch/async.rs

Useful for when you want to use the available time on the main thread.

Allow to check if systems are running, without waiting for them.

---

Cargo.toml
src/dispatch/stage.rs

Previously, the depdendency chain
```
A <- B <- C
```
could only be specified by adding an additional
dependency from C to A. Otherwise, it would give you
```
A <-- C
B
```
in the dispatcher.
Fixes slide-rs/specs#253

Fix bug with chained dependencies

---

.travis.yml
examples/par_seq.rs
src/dispatch/builder.rs
src/dispatch/mod.rs
src/dispatch/par_seq.rs
src/dispatch/stage.rs
src/dispatch/util.rs
src/lib.rs

This allows dispatching with zero virtual calls and maximum flexibility.
```rust
let mut dispatcher = ParSeq::new(
seq![
par![
SysA,
SysWithLifetime(&x),
seq![
SysC,
SysD,
],
],
SysB,
SysLocal(&x as *const u8),
],
&pool,
);
```

Add Par, Seq, ParSeq, par! and seq!

---

benches/bench.rs
examples/basic_dispatch.rs
examples/fetch_opt.rs
examples/seq_dispatch.rs
examples/thread_local.rs
src/dispatch/builder.rs
src/dispatch/dispatcher.rs
src/lib.rs
tests/dispatch.rs

This pull request changes the `DispatcherBuilder` API to have non-consuming `add_` methods in addition to the consuming `with_` methods. The old `add_` prefix was replaced by a `with_` prefix.
One open question is whether we want the `add_` methods to return `&mut Self` instead of `()`.
Need for this change arose from amethyst/amethyst#304. When standardizing the builder naming in Amethyst, we need non-consuming methods in order to pass Rusts borrow checker.
This is a breaking change.

Standardize builder naming

---

README.md

I forgot to update the example in the README file in #59.

Update readme example to new builder naming convention

---

src/dispatch/mod.rs
src/lib.rs

Noticed the build fail when I was trying specs on emscripten. Added missing cfg's to the parts requiring rayon like that was already done

Fix building on emscripten

---

Cargo.toml
src/dispatch/mod.rs
src/lib.rs

Closes #62 
I realized that this fix was not included in the latest version of `shred`. Please tell me if it works for you using `shred` 0.5.1 (I'll release once this PR is merged).

Backport emscripten fix to 0.5

---

src/dispatch/builder.rs

Signatures are different between v0.5 and master, so some tweaks were necessary to make these compatible.
r? @torkleyy

Allow RunNow for thread-local systems

---

Cargo.toml
src/dispatch/builder.rs
src/dispatch/dispatcher.rs
src/dispatch/mod.rs
src/dispatch/stage.rs
src/lib.rs

With the coming of `wasm32-unknown-unknown` it might be good idea to use `target_arch = "wasm32"` to detect whether to build with multithreading support or not.

Disable multithreading for all wasm32 targets.

---

examples/par_seq.rs
src/dispatch/builder.rs
src/dispatch/par_seq.rs
src/dispatch/stage.rs

This allows to quickly get a `ParSeq` structure without double and triple checking dependencies.

Add `print_par_seq`

---

Cargo.toml
examples/custom_bundle.rs
examples/derive_bundle.rs
shred-derive/Cargo.toml
shred-derive/src/lib.rs
src/dispatch/par_seq.rs
src/dispatch/stage.rs
src/res/mod.rs
src/system.rs
tests/dispatch.rs

Motivation for this change: Fetching with an id other than `0` is only possible outside a system or with a custom struct (which can only fetch a constant id). The plan was to use this for scripting, but resources added by scripts can easily be maintained by another resource, since access of those "script resources" is special anyways. This PR removes the unnecessary complexity and improves `Resources` access.
Resource ids were also a source of confusion in Specs where people thought that resource ids / component ids have something to do with entities.

Remove resource ids

---

Cargo.toml
examples/async.rs
examples/derive_bundle.rs
examples/generic_derive.rs
examples/seq_dispatch.rs
examples/thread_local.rs
shred-derive/Cargo.toml
shred-derive/src/lib.rs
src/dispatch/builder.rs
src/lib.rs
tests/dispatch.rs

This allows an in-scope re-exported `shred` crate to be used.
Closes #102
---
I'll test this in a larger project, give me a few days to get to it.

Remove `::` prefix from derived implementation.

---

.travis.yml
Cargo.toml
README.md
src/dispatch/builder.rs
src/dispatch/stage.rs
src/lib.rs
src/meta.rs
src/res/entry.rs
src/res/mod.rs

A small update of the `FxHashMap` `HashMap` to use the more perfomante `hashbrown` `HashMap`.
[`hashbrown`](https://github.com/Amanieu/hashbrown) is a Rust port of Google's high-performance SwissTable hash map and is around [2 times faster](https://github.com/Amanieu/hashbrown#features) than `FxHashMap`.

Update HashMaps to use hashbrown HashMap

---

src/world/mod.rs

Print warning if `World` is completely empty

---

benches/bench.rs
examples/async.rs
examples/basic_dispatch.rs
examples/custom_bundle.rs
examples/derive_bundle.rs
examples/dyn_sys_data.rs
examples/dynamic_resource_id.rs
examples/fetch_opt.rs
examples/par_seq.rs
examples/seq_dispatch.rs
examples/thread_local.rs
src/dispatch/dispatcher.rs
src/dispatch/par_seq.rs
src/lib.rs
src/meta.rs
src/world/entry.rs
src/world/mod.rs
tests/dispatch.rs
tests/dispose.rs
tests/nightly.rs

This allows to avoid confusion with the `WorldExt::new`
from Specs

Rename World::new to World::empty

---

src/cell.rs
src/world/mod.rs

Working on allowing [gluon](https://github.com/gluon-lang/gluon) to work with specs/shred and ended up needing to clone some `Fetch<EntitiesRes>` values. I don't know fully how specs/shred work internally but this should be equivalent to doing multiple `fetch` operations and should therefore be sound.

Make Fetch cloneable

---

src/world/mod.rs

The docs mention that `Debug` has to be implemented for a type for it to be a resource, but in code the bound is only `Any + Send + Sync`. Is this change correct? :smile:

Remove bound from documentation

---

benches/bench.rs
src/cell.rs
src/world/entry.rs
src/world/mod.rs

I know that `cell` is a small part of this library that is not really meant for consumption. However upon closer inspection, in my process to learn amethyst, I figured that I might have a change that could cause a tiny performance improvement that hopefully would ripple through-out all consumers of this library. 
The existing implementation of `Ref{,Mut}` had the implicit bound `T: Sized`. However internally the `T` was stored behind a reference, which means that it doesn't need to be sized to make `Ref{,Mut}` a sized struct. By removing this bound we can make `T` a `dyn Resource` instead of a `Box<Resource>`, which means that we remove a layer of indirection. This means that instead of having a `Fetch{,Mut}` with a `Ref{,Mut}<'_, Box<Resource>>`, we can rather give it `Ref{,Mut}<'_, dyn …

Remove box indirection in `Fetch{,Mut}`

---

Cargo.toml
src/cell.rs
src/dispatch/builder.rs
src/dispatch/dispatcher.rs
src/meta.rs
src/world/mod.rs

Also bumped to 0.9.0 due to recent breaking change (#138).

Move methods from `specs::WorldExt` to `World`

---

src/dispatch/batch.rs

Because panicking is general not unsafe, changes the doc comment of `BatchController::create` to better match the doc comment of the trait regarding safety.
As the implementers of the trait are supposed to be `Send` I added the requirement explicitly. 
I am still not sure why `Dispatcher` isn't `Send`, so I am not sure about the safety considerations.

Change wording in BatchController and impose Send requirements

---

src/dispatch/builder.rs
src/dispatch/dispatcher.rs

Seems like this was broken between `0.9.2` and `0.9.3`.
I'm not at all familiar with this code base, so please let me know if there is a better way to do this. That said, this compiles and unblocks my project locally.

Fix building without the "parallel" feature

---

shred-derive/Cargo.toml

Bumped `shred-derive` version to `0.6.2`.

---

CHANGELOG.md
Cargo.toml

`tynm 0.1.2` used the `todo!()` macro which is only stable in Rust 1.40. `tynm 0.1.3` switches that to `unimplemented!()` to be compatible with Rust 1.38.
This change ensures the fix is used (though consumers may already receive it simply with `cargo update`).

Bump `tynm` to `0.1.3` to be compatible with Rust 1.38.0.

---

src/dispatch/batch.rs

* Clarify safety of the `create` method.
* Link directly to the example on github; this saves some time searching
for it and it also avoids confusion in which repository the example
lives, as the trait is re-exported in `specs`.
Related to https://github.com/amethyst/specs/issues/689.
Please do check that what I state here is correct. It's gathered from reading other documentation and trying to understand it as a user of the library, but I didn't write the code.
I'm not updating the changelog, since there's no actual code change, just some documentation improvements. If you think this still requires an entry, I'll add it.
Also, am I right to assume that if I register a batch that contains some thread-local systems, they'll still be handled as `!Send` internally and nothing will allow the …

Improve docs of BatchController

---

Cargo.toml

[Changelog](https://github.com/rust-lang/hashbrown/blob/master/CHANGELOG.md#v080---2020-06-18)

Update hashbrown dependency v0.7.0 -> v0.8.2

---

CHANGELOG.md
examples/multi_batch_dispatching.rs
src/dispatch/batch.rs
src/dispatch/builder.rs
src/dispatch/mod.rs
src/lib.rs
src/meta.rs

Hello
As mentioned in #197, I've sketched some API how the batch dispatching could be improved so it's less awkward and doesn't require unsafe.
This is very much a PoC/WiP, I don't want to merge it as it is. I know there are missing docs, copy-pasted comments that are out of context, extra includes that are no longer needed, some things are public when in fact shouldn't be and in general a lot of garbage. I plan to clean it up before asking for it to get merged.
What I would like now is to have some feedback on the API. I have some specific questions, but any other suggestions are fine too:
* Naming. In particular, the simpler case where it is decided up-front how many times the sub-dispatcher should run is currently called multi-batch. I think this is a bad name, because it suggests it's …

WIP/PoC: Batch api ergonomics

---

CHANGELOG.md
Cargo.toml
shred-derive/Cargo.toml

Update crate versions to `0.11.0` and `0.6.3`.

---

Cargo.toml

error: Vulnerable crates found!
ID:       RUSTSEC-2021-0003
Crate:    smallvec
Version:  1.5.1
Date:     2021-01-08
URL:      https://rustsec.org/advisories/RUSTSEC-2021-0003

Update smallvec as there is a vulneraliby RUSTSEC-2021-0003

---

src/dispatch/builder.rs

For our system graph, it's possible that in the end no system actually needs to be executed at the  given moment. To avoid the overhead of calling ` dispatcher.dispatch(&world)` on an empty graph, I wanted to add an `is_empty` function that I can call before executing.
Similar, some systems may not need to run at some given time.  There are times in my code where a child task needs to run even if its dependency did not need to execute, and there are times where it doesn't need to run. In order to implement this logic, I added a `has_system` function so that I can check whether or not a dependency was skipped

Add getters to DispatcherBuilder

---

Cargo.toml
examples/dynamic_resource_id.rs
src/dispatch/builder.rs
src/dispatch/stage.rs
src/meta.rs
src/world/entry.rs
src/world/mod.rs
src/world/res_downcast/COPYRIGHT
src/world/res_downcast/LICENSE-APACHE
src/world/res_downcast/LICENSE-MIT
src/world/res_downcast/mod.rs
src/world/res_downcast/tests.rs

Fixes #217
- The previous implementation uses `mopa`, which has a known safety
issue: https://github.com/chris-morgan/mopa/issues/13
- This commit essentially inlines the code generated by
the `mopafy!` macro provided by `mopa`, thus removing the
dependency
- Since `mopa::Any` was part of the public interface of the `Resource`
trait, this is technically a breaking change
Thank you to @Cypher1 for reporting this issue

Eliminate safety issue in Resource::downcast*

---

.github/workflows/ci.yml
Cargo.toml
clippy.toml
examples/dyn_sys_data.rs
examples/dynamic_resource_id.rs
src/dispatch/async_dispatcher.rs
src/dispatch/batch.rs
src/dispatch/builder.rs
src/dispatch/stage.rs
src/lib.rs
src/meta.rs
src/system.rs
src/world/data.rs
src/world/mod.rs
src/world/res_downcast/mod.rs

Partially reverts 496564035390f085f677ed4e37852b1a5b4854cd (we use ahash again, but without using `hashbrown` which is just a copy of `std::collections::HashMap` with `ahash` as the default).

Use ahash instead of SipHash

---

.github/workflows/ci.yml
benches/bench.rs
src/cell.rs

Fixing some unsoundness, see commit messages.
I'm hoping to eventually [replace TrustCell with atomic_refcell::AtomicRefCell](https://github.com/amethyst/shred/pull/224), however that should probably wait on https://github.com/bholley/atomic_refcell/pull/18

TrustCell fixes

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
src/cell.rs

https://github.com/amethyst/shred/pull/223 accidentally regressed the debug impls, here we now show the referenced values again but the atomic counter is omitted

Update Debug impls for cell::Ref/cell::RefMut to show value (and bump MSRV)

---

.github/workflows/ci.yml
Cargo.toml
benches/bench.rs
clippy.toml
examples/basic_dispatch.rs
examples/dyn_sys_data.rs
src/lib.rs
src/meta.rs
src/world/res_downcast/mod.rs
tests/meta_table_safety_113.rs

Addresses miri's complaints about vtable shenanigans in MetaTable implementation.
* Before pointer casts and reads/deferences were used to extract/attach a vtable pointer as a `usize` (which includes operations that miri reports as UB). Now a function pointer is stored for each concrete type, this points to a function that knows the types involved and can thus leverage safe code to upcast a pointer from the concrete type to a trait object.
* `CastFrom` trait now uses a single method that operates on pointers rather than two separate methods for `&T` and `&mut T` (this is so that we don't have to store a separate function pointer for each case). Safety requirements for implementing `CastFrom` having been modified (but can be trivially met by just returning the provided pointer (letting it …

Fix remaining issues identified by Miri

---

Cargo.toml

The previous version had a bug, and was yanked.

Bump ahash dependency version

---

Cargo.toml

update aHash because of their license dependency and update tynm because their minimum version no longer builds in future rust compilers

Update aHash / tynm
